CREATE TABLE IF NOT EXISTS facts (
    id UUID PRIMARY KEY,
    fact VARCHAR(255) NOT NULL,
    source VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    user_id_fk UUID NOT NULL,
    likes_count INTEGER NOT NULL DEFAULT 0,
    dislikes_count INTEGER NOT NULL DEFAULT 0,
    super_likes_count INTEGER NOT NULL DEFAULT 0,
    is_disputed BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT user_id_fk FOREIGN KEY(user_id_fk) REFERENCES users(id)
);
